"""Chaos corpus replay engine for network resilience regression testing.

Replays a chaos corpus file through the network stack using deterministic
seeds to recreate the exact fault injection sequence that caused the
original failure.

Used by ``tests/test_corpus_replay.py`` for automated regression testing.
Chaos corpus files are generated by ``harness/grand_fuzzer/fuzzers/grand_e2e.py``.
"""

from __future__ import annotations

import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from harness.corpus import load_corpus, is_chaos_corpus


@dataclass
class ChaosReplayResult:
    """Result of replaying a chaos corpus."""

    success: bool
    error: str | None = None
    failure_kind: str | None = None
    failure_seq: int | None = None


class ChaosReplayEngine:
    """Replay a chaos corpus through the network stack.

    Uses deterministic seeds to recreate the exact fault injection
    sequence that caused the original failure.

    Parameters
    ----------
    corpus:
        Loaded corpus dict (from ``corpus.load_corpus``).
    """

    def __init__(self, corpus: dict):
        if not is_chaos_corpus(corpus):
            raise ValueError("ChaosReplayEngine requires a chaos corpus (version 2)")

        self.corpus = corpus
        self.seeds = corpus["seeds"]
        self.profile = corpus.get("chaos_profile", "standard")
        self.mode = corpus.get("mode", "lan_host")  # default for legacy corpus
        self.timeline = corpus.get("timeline", [])
        self.failure = corpus.get("failure", {})

        self.team_r_rgb = tuple(corpus.get("team_r_rgb", [64, 180, 232]))
        self.team_l_rgb = tuple(corpus.get("team_l_rgb", [255, 140, 0]))

    def replay(self) -> ChaosReplayResult:
        """Replay the scenario. Returns success/failure + details.

        Uses the exact seeds from the corpus to reproduce the fault
        injection sequence. If the bug is fixed, the replay should
        succeed where the original run failed.
        """
        # Import here to avoid circular deps and allow test isolation
        from harness.grand_fuzzer.fuzzers.grand_e2e import (
            GrandE2EFuzzer,
            ChaosProfile,
            SlaveMode,
        )

        # Map profile string to enum
        profile_map = {
            "gentle": ChaosProfile.GENTLE,
            "standard": ChaosProfile.STANDARD,
            "aggressive": ChaosProfile.AGGRESSIVE,
            "adversarial": ChaosProfile.ADVERSARIAL,
        }
        chaos_profile = profile_map.get(self.profile, ChaosProfile.STANDARD)

        # Map mode string to enum
        mode_map = {
            "local": SlaveMode.LOCAL,
            "lan_host": SlaveMode.LAN_HOST,
            "lan_guest": SlaveMode.LAN_GUEST,
            "lan_beacon_host": SlaveMode.LAN_BEACON_HOST,
            "lan_beacon_guest": SlaveMode.LAN_BEACON_GUEST,
            "lan_mdns_host": SlaveMode.LAN_MDNS_HOST,
            "lan_mdns_guest": SlaveMode.LAN_MDNS_GUEST,
            "online_host": SlaveMode.ONLINE_HOST,
            "online_guest": SlaveMode.ONLINE_GUEST,
        }
        slave_mode = mode_map.get(self.mode, SlaveMode.LAN_HOST)

        # Create fuzzer with exact settings from corpus
        fuzzer = GrandE2EFuzzer(
            seed=self.seeds["game"],
            mode=slave_mode,
            max_ply=120,
            chaos_profile=chaos_profile,
        )

        # Run a single game with explicit seeds from corpus
        result = fuzzer.run_game(
            game_seed=self.seeds["game"],
            fault_seed=self.seeds["fault"],
            timing_seed=self.seeds["timing"],
        )

        if result.success:
            return ChaosReplayResult(success=True)
        else:
            # Extract failure kind from message if possible
            failure_kind = None
            if "phase_setup" in result.message:
                failure_kind = "phase_setup"
            elif "send_failed" in result.message:
                failure_kind = "send_failed"
            elif "recovery" in result.message:
                failure_kind = "recovery_failed"

            return ChaosReplayResult(
                success=False,
                error=result.message,
                failure_kind=failure_kind,
                failure_seq=result.ply,
            )


def replay_chaos_corpus(corpus_path: Path) -> ChaosReplayResult:
    """Convenience function to replay a chaos corpus file.

    Parameters
    ----------
    corpus_path:
        Path to a ``.corpus.json`` file.

    Returns
    -------
    ChaosReplayResult with success status and error details.
    """
    corpus = load_corpus(corpus_path)
    engine = ChaosReplayEngine(corpus)
    return engine.replay()
