load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "relay",
    srcs = ["relay.py"],
    visibility = ["//:__subpackages__"],
    deps = [
        ":network",
        "@pip//websockets",
    ],
)

py_library(
    name = "network",
    srcs = [
        "__init__.py",
        "chessmatrix.py",
        "client.py",
        "discovery.py",
        "mdns.py",
        "protocol.py",
        "relay.py",
        "relay_client.py",
        "server.py",
        "validator.py",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        "//core",
        "//pieces",
        "@pip//chessmatrix",
        "@pip//numpy",
        "@pip//opencv_python",
        "@pip//websockets",
        "@pip//zeroconf",
    ],
)
