"""
Convert STL chess piece files to inline JS data for embedding in sim.html.

Uses vertex-clustering decimation (grid_res=20) to reduce triangle count ~10×
while keeping the mesh watertight (no holes). Outputs a JS snippet with:
  - STL_DATA: base64-encoded Float32 position arrays (9 floats per triangle)
  - _stlGeoFromB64(): decodes a base64 entry into a THREE.BufferGeometry

Usage:
    python3 tools/stl_to_inline.py > /tmp/stl_data.js
Then paste the output block into sim.html (replacing the old STL_DATA block).
"""
import struct, base64, sys, os

STL_DIR = os.path.join(os.path.dirname(__file__), '..', 'web', 'pieces', 'stl')
PIECES = ['Pawn', 'Rook', 'Knight', 'Bishop', 'Queen', 'King']
FNAMES = {'Pawn':'pawn.stl','Rook':'rook.stl','Knight':'knight.stl',
          'Bishop':'bishop.stl','Queen':'queen.stl','King':'king.stl'}
GRID_RES = 20  # ~1000-2200 output triangles per piece

def parse_binary_stl(path):
    tris = []
    with open(path, 'rb') as f:
        f.read(80)
        count = struct.unpack('<I', f.read(4))[0]
        for _ in range(count):
            data = f.read(50)
            if len(data) < 50: break
            vs = struct.unpack_from('<9f', data, 12)
            tris.append(((vs[0],vs[1],vs[2]),(vs[3],vs[4],vs[5]),(vs[6],vs[7],vs[8])))
    return tris

def decimate(tris, grid_res):
    """Vertex-clustering: merge nearby verts, drop degenerate/duplicate tris."""
    if not tris: return tris
    all_v = [v for tri in tris for v in tri]
    min_x=min(v[0] for v in all_v); max_x=max(v[0] for v in all_v)
    min_y=min(v[1] for v in all_v); max_y=max(v[1] for v in all_v)
    min_z=min(v[2] for v in all_v); max_z=max(v[2] for v in all_v)
    rx=max_x-min_x or 1e-9; ry=max_y-min_y or 1e-9; rz=max_z-min_z or 1e-9
    g=grid_res-1

    def cid(v):
        return (int((v[0]-min_x)/rx*g), int((v[1]-min_y)/ry*g), int((v[2]-min_z)/rz*g))

    cell_sum={}; cell_n={}
    for tri in tris:
        for v in tri:
            k=cid(v)
            if k not in cell_sum: cell_sum[k]=[v[0],v[1],v[2]]; cell_n[k]=1
            else:
                s=cell_sum[k]; s[0]+=v[0]; s[1]+=v[1]; s[2]+=v[2]; cell_n[k]+=1
    rep={k: tuple(s[i]/cell_n[k] for i in range(3)) for k,s in cell_sum.items()}

    result=[]; seen=set()
    for tri in tris:
        c0,c1,c2=cid(tri[0]),cid(tri[1]),cid(tri[2])
        if c0==c1 or c1==c2 or c0==c2: continue
        key=frozenset([c0,c1,c2])
        if key in seen: continue
        seen.add(key)
        result.append((rep[c0],rep[c1],rep[c2]))
    return result

def normalize(tris):
    """Center X/Z, bottom-align Y (min_y→0), scale to ≤0.70 XZ and ≤0.85 Y."""
    all_v=[v for tri in tris for v in tri]
    xs=[v[0] for v in all_v]; ys=[v[1] for v in all_v]; zs=[v[2] for v in all_v]
    cx=(min(xs)+max(xs))/2; miny=min(ys); cz=(min(zs)+max(zs))/2
    tris2=[tuple((v[0]-cx,v[1]-miny,v[2]-cz) for v in tri) for tri in tris]
    all_v2=[v for tri in tris2 for v in tri]
    xs2=[v[0] for v in all_v2]; ys2=[v[1] for v in all_v2]; zs2=[v[2] for v in all_v2]
    wx=max(xs2)-min(xs2); wy=max(ys2)-min(ys2); wz=max(zs2)-min(zs2)
    scale=min(0.70/(max(wx,wz) or 1e-9), 0.85/(wy or 1e-9))
    return [tuple((v[0]*scale,v[1]*scale,v[2]*scale) for v in tri) for tri in tris2]

def pack_floats(tris):
    buf=bytearray()
    for tri in tris:
        for v in tri:
            buf+=struct.pack('<fff',v[0],v[1],v[2])
    return bytes(buf)

print('// AUTO-GENERATED by tools/stl_to_inline.py — do not edit by hand')
print('// Vertex-clustering decimated STL geometry for 3D chess pieces')
print('const STL_DATA={')
for ptype in PIECES:
    fname=FNAMES[ptype]
    path=os.path.join(STL_DIR,fname)
    if not os.path.exists(path):
        print(f'  // ERROR: {ptype} missing at {path}',file=sys.stderr)
        continue
    tris=parse_binary_stl(path)
    dec=decimate(tris,GRID_RES)
    norm=normalize(dec)
    raw=pack_floats(norm)
    b64=base64.b64encode(raw).decode('ascii')
    print(f'  {ptype}:"{b64}",')
    print(f'  // {ptype}: {len(tris)}→{len(norm)} tris, {len(raw)//1024}KB, {len(b64)//1024}KB b64',
          file=sys.stderr)
print('};')
print()
print('// Decode a STL_DATA entry into a THREE.BufferGeometry (positions only; normals computed).')
print('function _stlGeoFromB64(b64){')
print('  const bin=atob(b64),buf=new ArrayBuffer(bin.length),bytes=new Uint8Array(buf);')
print('  for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);')
print('  const geo=new THREE.BufferGeometry();')
print('  geo.setAttribute("position",new THREE.BufferAttribute(new Float32Array(buf),3));')
print('  geo.computeVertexNormals();')
print('  return geo;')
print('}')
