filegroup(
    name = "chessmatrix_scanner_js",
    srcs = ["chessmatrix-scanner.js"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "chess_engine_js",
    srcs = ["chess-engine.js"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sim_html",
    srcs = ["sim.html"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "spectator_html",
    srcs = ["spectator.html"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "spectator_engine_js",
    srcs = ["spectator-engine.js"],
    visibility = ["//visibility:public"],
)
